// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System.Reflection;
[assembly: AssemblyVersion("1.41.1.493")]
[assembly: AssemblyFileVersion("1.41.1.493")]
[assembly: AssemblyInformationalVersion("1.41.1.493+293b0c0")]
