// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System.Reflection;
[assembly: AssemblyVersion("1.41.5.495")]
[assembly: AssemblyFileVersion("1.41.5.495")]
[assembly: AssemblyInformationalVersion("1.41.5.495+4c76e4f")]
