// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System.Reflection;
[assembly: AssemblyVersion("1.40.490")]
[assembly: AssemblyFileVersion("1.40.490")]
[assembly: AssemblyInformationalVersion("1.40.490+bb8f4f9")]
